site_name: LiveKit Tutorials
site_url: https://livekit-tutorials.openvidu.io
site_description: Discover comprehensive LiveKit tutorials for building real-time audio and video apps. Explore client and server guides for multiple platforms.
repo_name: openvidu/openvidu-livekit-tutorials
repo_url: https://github.com/openvidu/openvidu-livekit-tutorials

nav:
  - index.md
  - Application Client:
      - tutorials/application-client/index.md
      - JavaScript: tutorials/application-client/javascript.md
      - React: tutorials/application-client/react.md
      - Angular: tutorials/application-client/angular.md
      - Vue: tutorials/application-client/vue.md
      - Electron: tutorials/application-client/electron.md
      - Ionic: tutorials/application-client/ionic.md
      - Android: tutorials/application-client/android.md
      - iOS: tutorials/application-client/ios.md
  - Application Server:
      - tutorials/application-server/index.md
      - Node.js: tutorials/application-server/node.md
      - Go: tutorials/application-server/go.md
      - Ruby: tutorials/application-server/ruby.md
      - Java: tutorials/application-server/java.md
      - Python: tutorials/application-server/python.md
      - Rust: tutorials/application-server/rust.md
      - PHP: tutorials/application-server/php.md
      - .NET: tutorials/application-server/dotnet.md
  - Advanced Features:
      - tutorials/advanced-features/index.md
      - Recording Basic: tutorials/advanced-features/recording-basic.md
      - Recording Advanced: tutorials/advanced-features/recording-advanced.md
  - What is OpenVidu?: about-openvidu.md
  - OpenVidu vs LiveKit: openvidu-vs-livekit.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.footer
    # - navigation.expand
    # - navigation.path
    # - navigation.sections
    - navigation.top
    - navigation.indexes
    # - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    # - header.autohide
  font:
    text: Tomorrow # Nunito Sans, Rubik, Barlow, Raleway, Open Sans, Tomorrow, IBM Plex Sans
    code: Roboto Mono
  favicon: assets/images/logo.png
  logo: assets/images/openvidu_globe_bg_transp_cropped.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      autoplayVideos: true
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - do-not-include-in-gallery
      auto_caption: false
      caption_position: bottom
      background: none
      shadow: false

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.snippets:
      url_download: true
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/OpenVidu
    - icon: simple/x
      link: https://x.com/openvidu
    - icon: simple/medium
      link: https://openvidu.medium.com/
    - icon: simple/youtube
      link: https://www.youtube.com/@openvidu
  scope: /
  consent:
    title: Cookie consent
    description: >
      This website uses cookies to ensure you get the best experience on our website.
      <a href="/conditions/cookie-policy/" target="_blank">See cookie policy</a>
    cookies:
      analytics: Google Analytics

extra_css:
  - stylesheets/colors.css
  - stylesheets/extra.css
  - stylesheets/unsemantic-grid.css
  - stylesheets/livekit-tutorials.css
  - stylesheets/amplify.css

copyright: >
  2025 &copy; OpenVidu –
  <a href="#__consent">Change cookie settings</a>
